spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testSQL
    username: postgres
    password: Hewlett123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080